@echo off
echo Installing Flask...
pip install flask
echo Installing PyWin32...
pip install pywin32
echo Installing Python-dateutil...
pip install python-dateutil
echo Installing Requests (for testing)...
pip install requests
echo.
echo Package installation complete!
pause
