services:
  - type: web
    name: greenfield-inventory-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
    healthCheckPath: /api/stats
    autoDeploy: true